<a href="https://colab.research.google.com/github/vasudevnethikar-design/sample-data-structure/blob/main/numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORT NUMPY IN PYTHON**

In [1]:
import numpy as np


**numpy array creation**

In [2]:
list1 = [1,2,3,4,5,56]
array1=np.array(list1)
print(array1)

[ 1  2  3  4  5 56]


In [3]:
array2=np.array([1,4,2,3])
print(array2)

[1 4 2 3]


**create a 2d array**

In [7]:
array3=np.array([[1,2,3,4],[4,3,21,0]])
print(array3)

[[ 1  2  3  4]
 [ 4  3 21  0]]


**create a 3d array**

In [10]:
array4=np.array([[[1,2,3,4],[4,3,2,1],[3,4,2,1]],[[1,5,6,7],[7,6,5,4],[5,4,3,2]]])
print(array4)

[[[1 2 3 4]
  [4 3 2 1]
  [3 4 2 1]]

 [[1 5 6 7]
  [7 6 5 4]
  [5 4 3 2]]]


**check the data type of array**

In [11]:
print(array3.dtype)

int64


**to check the dimensions of array **

In [12]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)

1
1
2
3


**To check the size  of array**

In [15]:
print(array1.size)
print(array2.size)
print(array3.size)
print(array4.size)







6
4
8
24


**numpy shape attribute**

In [16]:
print(array2.shape)
print(array3.shape)
print(array4.shape)

(4,)
(2, 4)
(2, 3, 4)


**numpy array itemsize**

In [17]:
print(array2.itemsize)
print(array3.itemsize)
print(array4.itemsize)

8
8
8


In [18]:
array2=np.array([1,2,3,4],dtype=np.int32)
print(array2.itemsize)

4


**Data attribute**

In [20]:
print("data of array2 is at ",array2.data)

data of array2 is at  <memory at 0x7c0290a3de40>


**array numpy index modification**

In [21]:
print(array2[-1])
array1[2]=14
print(array1)

4
[ 1  2 14  4  5 56]
