<a href="https://colab.research.google.com/github/vasudevnethikar-design/sample-data-structure/blob/main/numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORT NUMPY IN PYTHON**

In [ ]:
import numpy as np


**numpy array creation**

In [ ]:
list1 = [1,2,3,4,5,56]
array1=np.array(list1)
print(array1)

[ 1  2  3  4  5 56]


In [ ]:
array2=np.array([1,4,2,3])
print(array2)

[1 4 2 3]


**create a 2d array**

In [ ]:
array3=np.array([[1,2,3,4],[4,3,21,0]])
print(array3)

[[ 1  2  3  4]
 [ 4  3 21  0]]


**create a 3d array**

In [ ]:
array4=np.array([[[1,2,3,4],[4,3,2,1],[3,4,2,1]],[[1,5,6,7],[7,6,5,4],[5,4,3,2]]])
print(array4)

[[[1 2 3 4]
  [4 3 2 1]
  [3 4 2 1]]

 [[1 5 6 7]
  [7 6 5 4]
  [5 4 3 2]]]


**check the data type of array**

In [ ]:
print(array3.dtype)

int64


**to check the dimensions of array **

In [ ]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)


NameError: name 'array1' is not defined

**To check the size  of array**

In [ ]:
print(array1.size)
print(array2.size)
print(array3.size)
print(array4.size)







6
4
8
24


**numpy shape attribute**

In [ ]:
print(array2.shape)
print(array3.shape)
print(array4.shape)

(4,)
(2, 4)
(2, 3, 4)


**numpy array itemsize**

In [ ]:
print(array2.itemsize)
print(array3.itemsize)
print(array4.itemsize)

8
8
8


In [ ]:
array2=np.array([1,2,3,4],dtype=np.int32)
print(array2.itemsize)

4


**Data attribute**

In [ ]:
print("data of array2 is at ",array2.data)

data of array2 is at  <memory at 0x7c0290a3de40>


**array numpy index modification**

In [ ]:
print(array2[-1])
array1[2]=14
print(array1)

4
[ 1  2 14  4  5 56]


**compute mean using numpy **

In [ ]:
import numpy as np


In [ ]:
marks = np.array([15,20,30,43,51,60])
print("mean value is")
print(np.mean(marks))
print("midena value is")
print(np.median(marks))
print("standard value is")
print(np.std(marks))

mean value is
36.5
midena value is
36.5
standard value is
16.235249715767644


In [ ]:
print("for prcentage is")
print(np.percentile(marks,77))

for prcentage is
49.8


In [ ]:
print("min value and max value")
print(np.min(marks))
print("max value and max value")
print(np.max(marks))



min value and max value
15
max value and max value
60


In [ ]:
list1 = [1,2,3,4,5,56]
array1=np.array(list1)
array2=np.array([1,4,2,3])
array3=np.array([[1,2,3,4],[4,3,21,0]])
array4=np.array([[[1,2,3,4],[4,3,2,1],[3,4,2,1]],[[1,5,6,7],[7,6,5,4],[5,4,3,2]]])

In [ ]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)
print(array1.nbytes)

1
1
2
3
48
